version: '3.8'

services:
  # App storybook service
  storybook:
    build:
      context: frontend
      dockerfile: ./Dockerfile.storybook
      target: storybook
    ports:
      - "6006:8080"
    restart: always
    environment:
      PORT: 8080
    networks:
      - frontend
  # App frontend service
  front:
    build:
      context: frontend
      dockerfile: ./Dockerfile.web
    ports:
      - "8888:3000"
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: 3000
      API_URL: backend:3000
    networks:
      - frontend
  # App backend service
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/me-conta
    networks:
      - backend
      - frontend
  # Database Service (postgres)
  db:
    image: postgres:latest
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: 'me-conta'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - me-conta-data:/var/lib/database
    networks:
      - backend
volumes:
  me-conta-data:
networks:
  backend:
  frontend:
