name: Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  analysis:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: nouchka/sqlite3:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
  storybook:
      runs-on: ubuntu-latest
      needs:
        - analysis
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Login no Heroku Container
          working-directory: frontend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:login
        - name: Build Docker image
          working-directory: frontend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
            PORT: 8080
          run: |
            docker build . -f Dockerfile.storybook -t storybook --build-arg PORT
            docker tag storybook registry.heroku.com/${{ secrets.HEROKU_STORYBOOK_APP_NAME }}/web
        - name: Push Docker image to Heroku
          working-directory: frontend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: docker push registry.heroku.com/${{ secrets.HEROKU_STORYBOOK_APP_NAME }}/web
        - name: Release to Heroku
          working-directory: frontend
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: heroku container:release -a ${{ secrets.HEROKU_STORYBOOK_APP_NAME }} web