name: Show-Infos
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Set up
      env:
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_BACKEND_APP_NAME: ${{ secrets.HEROKU_BACKEND_APP_NAME }}
        HEROKU_FRONTEND_APP_NAME: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
        HEROKU_STORYBOOK_APP_NAME: ${{ secrets.HEROKU_STORYBOOK_APP_NAME }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo $ADMIN_EMAIL >> secrets.txt
        echo $ADMIN_PASSWORD >> secrets.txt
        echo $API_URL >> secrets.txt
        echo $DATABASE_URL >> secrets.txt
        echo $HEROKU_API_KEY >> secrets.txt
        echo $HEROKU_API_KEY >> secrets.txt
        echo $HEROKU_BACKEND_APP_NAME >> secrets.txt
        echo $HEROKU_FRONTEND_APP_NAME >> secrets.txt
        echo $HEROKU_STORYBOOK_APP_NAME >> secrets.txt
        echo $NODE_ENV >> secrets.txt
        echo $SONAR_TOKEN >> secrets.txt
        pwd

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
